<?php

use Drupal\Core\Logger\LoggerChannelFactoryInterface;

/**
 * Implements hook_form_alter().
 */
function eksponent_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  // kpr($form['#id']);
  if ($form_id === 'views_exposed_form' && isset($form['#id']) && $form['#id'] == 'views-exposed-form-event-overview-page-1') {

    if (isset($form['actions']['submit'])) {
      $form['actions']['submit']['#value'] = t('Search');
    }
  }
}


/**
 * Implements hook_preprocess_views_view_field().
 */
function eksponent_preprocess_views_view_field(array &$variables) {
  // Ensure we're targeting the correct View and field.
  if ($variables['view']->id() == 'event_overview' && $variables['field']->field == 'field_tickets_available') {
    // Safely retrieve the row data.
    $row = $variables['row'];

    // Make sure the entity exists in the row data.
    if (isset($row->_entity)) {
      // Get the value of the 'field_tickets_available' field.
      $field_value = $row->_entity->get('field_tickets_available')->value;

      // Check if the field value is zero and rewrite it.
      if ($field_value == 0) {
        $variables['output'] = t('<span class="soldout">Sold Out</span>');
      }
      if ($field_value > 0 && $field_value < 10) {
        $variables['output'] = t('<span class="less10">'.$field_value . ' seats left</span>');
      }
      if ($field_value >= 10) {
        $variables['output'] = t('<span class="over10">&nbsp;</span>');
      }
    }
  }
}
